name: My First Action

on: push # Runs when code is pushed

jobs:
  my-new-job: #Here you put the name of the job
    runs-on: ubuntu-latest # The CI-CD pipeline will run on Ubuntu
    env:
      NUMBER1: "121" # First number
      NUMBER2: "111" # Second number # Define a number manually
    steps:
      - name: Checkout code
        run: git clone https://github.com/berezovsky13/nodejs.git # Gets the latest code, in other words it does 'git clone'

      - name: Checkout the nodejs repository
        uses: actions/checkout@v4
        with:
          repository: "berezovsky13/nodejs" # Specific repository URL

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18" # Set to the required Node.js version

      - name: Install Dependencies
        run: npm install # Install project dependencies

      - name: Run Tests (if applicable)
        run: npm test # Runs tests if defined

      - name: Verify Pipeline Success
        run: echo "Pipeline executed successfully!"

      - name: Checkout code To Raz
        run: git clone https://github.com/raz-project/jenkins2.git # Gets the latest code, in other words it does 'git clone'

      - name: Checkout code Raz Auto
        uses: actions/checkout@v4 # It just does git clone but for the repo that you are currently using

      - name: Check DNS Resolution
        run: nslookup google.com

      - name: Ping Google DNS
        run: curl -Is https://google.com | head -n 1

      - name: List Files and Directories
        run: ls -la # Lists all files and directories in the workspace

      - name: Show Israel Date and Time
        run: |
          TZ="Asia/Jerusalem" date
        id: date_time # Store output for later use

      - name: Run Palindrome Check
        run: |
          RESULT=$(NUMBER1=${{ env.NUMBER1 }} NUMBER2=${{ env.NUMBER2 }} python3 test.py)
          echo "RESULT=$RESULT" >> $GITHUB_ENV
        id: palindrome_check

      - name: Display Outputs
        run: |
          echo "Israel Date and Time: ${{ steps.date_time.outputs.stdout }}"
          echo "Palindrome Check Output: ${{ steps.palindrome_check.outputs.stdout }}"

      - name: Print Hello World
        run: echo "Hello, GitHub Actions!" # This is just the command
